### PR TITLE
Base address added for Asus N56VZ

### PR DESCRIPTION
**Pull request by jljouannic**
The process you indicate seems to also work for Asus N56VZ so I added a few information about it in the README file.

### CODE REVIEW

**Comment by marioux** [comment]
For the bios version N56VZ.204
IGDM_BASE=0xc68b0018
DIDL_OFFSET=0x120
CADL_OFFSET=0x160

**Comment by flowernert** [comment]
Hi there, after a few kernel panic I finally achieved to make it works on my N56VZ.204
IGDM_BASE=0xAE8B0018
DIDL_OFFSET=0x120
CADL_OFFSET=0x160

**Comment by FrostbittenKing** [comment]
On 11/29/2012 07:06 PM, krustymars wrote:

> Hi there, after a few kernel panic I finally achieved to make it works on my N56VZ.204
> IGDM_BASE=0xAE8B0018
> DIDL_OFFSET=0x120
> CADL_OFFSET=0x160
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/FrostbittenKing/fixasusbacklight/pull/2#issuecomment-10859159
> 
> Hmm, ok thats strange. This guys laptop below (same laptop + bios
> version) has a different IGDM_BASE address.
> 
> marioux commented 15 days ago
> For the bios version N56VZ.204
> IGDM_BASE=0xc68b0018
> DIDL_OFFSET=0x120
> CADL_OFFSET=0x160

Seems like the offset is influenced by the amount of memory installed.
Idk exactly how and when. On the ux31a and the 32vd it doesn't change
the address. But whatever. As soon as kernel 3.7 hits the repos my fix
is obsolete :).

**Comment by cyf-zz** [comment]
Think this will work for UX21A?

**Comment by FrostbittenKing** [comment]
It should, if the UX21A has the same buggy bios (which I guess). You just need to determine the correct IGDM base address.

**Pull request merged**
